### ISSUE TITLE
No RPC Url available for chainId

### ISSUE THREAD

**Issue by Shuunen** [SoxZz5/next-web3-boilerplate#1]
I just went to https://next-web3-boilerplate-nine.vercel.app

Clicked on the button & got this in console : 

```text
940-f40191caf500eeb2.js:74 Uncaught (in promise) Error: No RPC Url available for chainId: 137
    at Ue.updateRpcUrl (940-f40191caf500eeb2.js:74:164814)
    at Ue.initialize (940-f40191caf500eeb2.js:74:165197)
    at new Ue (940-f40191caf500eeb2.js:74:162128)
    at 0a6e12db-0b2355fff7ee292f.js:1:236341
    at 0a6e12db-0b2355fff7ee292f.js:1:4843
    at Object.next (0a6e12db-0b2355fff7ee292f.js:1:4948)
    at 0a6e12db-0b2355fff7ee292f.js:1:3885
    at new Promise (<anonymous>)
    at Module.l (0a6e12db-0b2355fff7ee292f.js:1:3630)
    at 0a6e12db-0b2355fff7ee292f.js:1:235968
```

Any ideas ?

**Comment by SoxZz5** [comment]
Have you got metamask installed ?

**Comment by SoxZz5** [comment]
Ok you right walletconnect is on bad RPC have to change it will push it soon

**Comment by SoxZz5** [comment]
Must work now, but it's a normal issue, since Walletconnect don't handle Mumbai which is chainId 80001, while metamask is working, but if you change NEXT_PUBLIC_BC_ENV to "production" must work just redeployed vercel
